config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "welcome#home"

  get '/awesome_things', to: 'welcome#awesome_things', as: 'awesome_things'
  get '/do_super_user_things', to: 'welcome#do_super_user_things', as: 'do_super_user_things'
  get '/do_owner_things', to: 'welcome#do_owner_things', as: 'do_owner_things'
  
  resources :registrations, only: [:new, :create]
  resources :users, only: [:index, :show, :destroy]

  put '/users/:id/change_account_role', to: 'users#change_account_role', as: 'change_account_role'

  get '/sessions/new', to: 'sessions#new', as: 'new_session'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions', to: 'sessions#destroy', as: 'session'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password 
  validates :first_name, :last_name, :username, :email, presence: true
  validates :username, :email, uniqueness: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  enum role: {
    basic: 0, 
    moderator: 1, 
    admin: 2, 
    super_user: 3, 
    owner: 4
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  private

    def logged_in? 
      !!current_user
    end 

    def current_user 
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def is_owner?
      if current_user.role != "owner" 
        flash[:error] = "You are not an owner"
        redirect_back(fallback_location: root_path)
      end
    end

    def authenticate_user
      redirect_to root_path if !logged_in?
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController 
  
  def new 
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id 
      flash[:notification] = "Account created!"
      redirect_to root_path 
    else 
      flash[:error] = @user.errors 
      render :new 
    end
  end

  private 

    def user_params 
      params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    def new 
        @user = User.new
    end 

    def create 
        @user = User.where("lower(username) = ?", params[:user][:username].downcase).first
        binding.pry
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id 
            flash[:notification] = "Successfully logged in!"
            redirect_to root_path
        else 
            flash[:error] = "Unable to log in"
            render :new 
        end
    end

    def destroy
        session.clear 
        flash[:notification] = "Successfully logged out!"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_action :authenticate_user
  before_action :is_owner?, only: [:index, :change_account_role]

  def index 
      @users = User.all
  end

  def change_account_role
    @user = User.find_by(id: params[:id])
    if @user && @user.update(role: params[:role].to_i)
      flash[:notification] = "#{@user.username} is now a #{@user.role}!"
    else 
      flash[:notification] = "There was an issue with this request!"
    end
    redirect_to users_path
  end

  def show 
  end 

  def destroy 
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def home
  end

  def awesome_things 
    redirect_to "https://www.google.com/search?q=awesome+things&source=lnms&tbm=isch&sa=X&ved=0ahUKEwik2f_9g57UAhUB7CYKHdNqCZsQ_AUICigB&biw=614&bih=648&dpr=2"
  end

  def do_super_user_things 
    if current_user.role_before_type_cast >= 3
      redirect_to "http://www.washingtonpost.com"
    else 
      flash[:error] = "You must be a super user to access this!"
      redirect_to root_path 
    end 
  end

  def do_owner_things 
    if current_user.role == "owner"
      redirect_to "http://learn.co"
    else 
      flash[:error] = "You are not an owner!"
      redirect_to root_path 
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <!-- 
        if a user is logged in they can go do awesome things 
        else the can go to a login or signup screen 
      -->
    <div class="navbar">
      <% if logged_in? %>
        <%= link_to "Awesome Things", awesome_things_path %>
        <% if current_user.role_before_type_cast >= 3 %>
          <%= link_to "Do Super User Things", do_super_user_things_path %>
        <% end %>
        <% if current_user.role == "owner" %>
          <%= link_to "Do Owner Things", do_owner_things_path %>
          <%= link_to "User Accounts", users_path %>
        <% end %>
        <%= button_to "Logout", { controller: 'sessions', action: "destroy" }, method: :delete %>
      <% else %>
        <%= link_to "Login", new_session_path %>
        <%= link_to "Signup", new_registration_path %>
      <% end %>
    </div>
    
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
      <% end %>
    <% end %>

    <div class="main-content">
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/index.html.erb
<h1>You must be an owner if you are here, congratulations!!</h1>

<% @users.each do |user| %>
  <div style="border: 1px solid black; margin: 12px;">
    <h2><%= user.username %></h2>
    <p>role: <%= user.role %></p>
    <% if user.role_before_type_cast < 2 %>
      <%= button_to "Upgrade To Admin", { controller: 'users', id: user.id, role: 2, action: "change_account_role" }, method: :put %>
    <% end %>
    <% if user.role_before_type_cast < 3 %>
      <%= button_to "Upgrade To Super User", { controller: 'users', id: user.id, role: 3, action: "change_account_role" }, method: :put %>
    <% end %>
    <% if user.role_before_type_cast > 2 %>
      <%= button_to "Downgrade to Admin", { controller: 'users', id: user.id, role: 2, action: "change_account_role" }, method: :put %>
    <% end %>
  </div> 
<% end %>

app/views/welcome/home.html.erb
<h1>Welcome to the Authentication Application</h1>